### PR TITLE
chore: merge v0.23

### PR DESCRIPTION
**Pull request by strophy**
## Issue being fixed or feature implemented

We need to be able to deploy newer builds of Dash Core with v0.24 devnets before v0.23 is released

## What was done?

Merge `v0.23-dev` into `v0.24-dev`

## How Has This Been Tested?

Untested

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by shumkov** [comment]
@strophy since you are an admin of this repository I would recommend merging master -> v0.23-dev -> v0.24-dev directly with git. It's much more convenient, especially in case of conflicts.

**Comment by shumkov** [comment]
Closed due to the merged preformed directly in git

**Comment by strophy** [comment]
I don't understand what I am supposed to do @shumkov you mean merge and push to the branches without making a PR? I thought we have rules to prevent that?

**Comment by shumkov** [comment]
Yes, for merging master and dev branches on each other it's fine.

**Pull request closed without merging**
